### ISSUE TITLE
dataset_npy问题

### ISSUE THREAD

**Issue by tryoeryd** [WHU-ZQH/KGAN#1]
你好，请问怎么使用四个git-lfs文件或者怎么将git-lfs文件转化成npy和npz文件，非常感谢解答

**Comment by WHU-ZQH** [comment]
你好，在dataset_npy分支下面提供的这几个文件就是npy和npz文件，请注意文件后缀，下载下来就是npy和npz文件

**Comment by tryoeryd** [comment]
好的    非常感谢
