### ISSUE TITLE
源码有50%借鉴一篇ACL的文章，请问具体是哪篇啊？单搜TNet-ATT搜不到

### ISSUE THREAD

**Issue by chenmiaozi-maker** [WHU-ZQH/KGAN#14]

**Comment by chenmiaozi-maker** [comment]
找到了，是这篇：Progressive Self-Supervised Attention Learning for Aspect-Level Sentiment Analysis

**Comment by ewgfsd** [comment]
请问，复现模型的bert实现了吗？准确率多少？
