### ISSUE TITLE
图文件问题

### ISSUE THREAD

**Issue by ewgfsd** [WHU-ZQH/KGAN#18]
请问semeval_laptop_graph_analogy.pkl这种文件是怎么生成的？有相应的代码么？

**Comment by WHU-ZQH** [comment]
知识图谱embedding文件已上传至google drive: https://drive.google.com/drive/folders/1JFh16NNac5KUHOy4Hd3GKLH6_hghhbHC

具体生成.pkl文件的代码在get_embedding函数（https://github.com/WHU-ZQH/KGAN/blob/v2.0/utils.py ，Line 621-707）
