### ISSUE TITLE
entity_embeddings的问题

### ISSUE THREAD

**Issue by Morihako** [WHU-ZQH/KGAN#2]
您好，我现在在使用您的程序训练，我目前成功训练了Restaurant和Laptop，Twitter的数据集我在论文原作者那找到了。但是代码中的entity_embeddings_distmult_200.txt和entity_embeddings_analogy_400.txt我现在不知道可以在哪找到，搜索了一下也没有看到，请问您能否分享一下这两个文件的下载链接或者告知我获取方式吗？非常感谢您的解答。

**Comment by WHU-ZQH** [comment]
由于文件太大，我已经把文件上传到google drive，供大家下载：)
