### ISSUE TITLE
模型的bert实现

### ISSUE THREAD

**Issue by syydhhd** [WHU-ZQH/KGAN#3]
您好，我目前在使用您的模型进行训练，但是关于模型的Bert实现我并没有在代码中找到，请问模型的Bert实现何时能够分享？

**Comment by WHU-ZQH** [comment]
你好，由于之前论文提交比较匆忙，所以程序有一些文件没有整理好，十分抱歉。我这两天把程序整理好后，重新上传到github项目中，请关注项目更新，谢谢~



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: syydhhd ***@***.***&gt;
发送时间: 2022年4月18日 16:45
收件人: WHU-ZQH/KGAN ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [WHU-ZQH/KGAN] 模型的bert实现 (Issue #3)





 
您好，我目前在使用您的模型进行训练，但是关于模型的Bert实现我并没有在代码中找到，请问模型的Bert实现何时能够分享？

**Comment by WHU-ZQH** [comment]
BERT代码已更新：)
