### ISSUE TITLE
关于三个数据集的图嵌入文件

### ISSUE THREAD

**Issue by tryoeryd** [WHU-ZQH/KGAN#4]
你好，请问14semeval_laptop_graph_analogy.pkl这种文件是怎么生成的？非常感谢

**Comment by WHU-ZQH** [comment]
文件上传到google drive（https://drive.google.com/drive/folders/1JFh16NNac5KUHOy4Hd3GKLH6_hghhbHC?usp=sharing）中了，可以直接下载使用：）
