### ISSUE TITLE
作者你好，跑bert+kgnn的时候这里可能有些问题，调用build_dataset时漏了graph_embeddings(在utils的521行那里)

### ISSUE THREAD

**Issue by 2Fgithub** [WHU-ZQH/KGAN#5]
https://github.com/WHU-ZQH/KGAN/blob/8b76b0e9715787d415c45b5e64aa86d02a1c27ed/main_total.py#L163

**Comment by WHU-ZQH** [comment]
谢谢提醒，已经更新了utils.py代码，请重新运行，有问题可以及时沟通:)

**Comment by 2Fgithub** [comment]
好的，谢谢。还有一个可能的问题是nn.utils中的get_batch_input_Bert和 train_bert中调用get_batch_input_Bert参数对不太上

**Comment by WHU-ZQH** [comment]
好的，已更新nn_utils.py

**Comment by syydhhd** [comment]
@2Fgithub 请问你成功复现原模型的bert实现了吗？我虽然成功的运行了代码，但是模型效果却很差

**Comment by 2Fgithub** [comment]
我还没有，运行bert嵌入的时候报错，嵌入长度过长，我在GitHub上也有提到，但我不知道怎么改，你有遇到过吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WHU-ZQH/KGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WHU-ZQH/KGAN] 作者你好，跑bert+kgnn的时候这里可能有些问题，调用build_dataset时漏了graph_embeddings(在utils的521行那里) (Issue #5)





 
@2Fgithub 请问你成功复现原模型的bert实现了吗？我虽然成功的运行了代码，但是模型效果却很差

**Comment by syydhhd** [comment]
@2Fgithub 我运行代码时并没有遇到这样的问题，只是一开始dim_k设为300时报了错，改成768之后就好了

**Comment by 2Fgithub** [comment]
你好，请问bert效果不好的问题你解决了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月6日(星期五) 上午8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WHU-ZQH/KGAN] 作者你好，跑bert+kgnn的时候这里可能有些问题，调用build_dataset时漏了graph_embeddings(在utils的521行那里) (Issue #5)





 
@2Fgithub 我运行代码时并没有遇到这样的问题，只是一开始dim_k设为300时报了错，改成768之后就好了

**Comment by syydhhd** [comment]
@2Fgithub 并没有解决，我尝试了很多参数，并对模型进行了一定的简化，但是发现模型效果依旧表现极差。

**Comment by WHU-ZQH** [comment]
感谢大家指出的这些问题，由于我最近忙着投稿，有些问题未能及时回复，十分抱歉。预计下周左右，我将更新code，提供当时训练的超参数设置，希望能够帮助大家~

**Comment by Inactionzz** [comment]
@syydhhd 请问你

> @2Fgithub 并没有解决，我尝试了很多参数，并对模型进行了一定的简化，但是发现模型效果依旧表现极差。

请问你现在成功复现论文效果了吗

**Comment by wuQi-666** [comment]
> 好的，谢谢。还有一个可能的问题是nn.utils中的get_batch_input_Bert和 train_bert中调用get_batch_input_Bert参数对不太上

你好，同样遇到这个问题，请问怎么解决的？感谢
