### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by KokiaY** [WHU-ZQH/KGAN#9]
您好，下载了您的代码，但是没有看见twitter数据集，请问Twitter数据集在哪可以下载；另外entity_embeddings文件应该放在哪个位置呢。万分感谢！！！

**Comment by Morihako** [comment]
Twitter数据集去《Adaptive Recursive Neural Network for Target-dependent Twitter Sentiment Classification》原作者给的地址去下载就可以了：https://docs.google.com/forms/d/e/1FAIpQLSd6HhEitpzv-vpdrB63Jbx-fYWohnOZRCUb0ibKjpO21Q_tIQ/viewform
不过下载下来之后还需要自己处理成这篇论文使用的格式。entity_embeddings放在/embeddings文件夹里，用的时候去utils修改一下路径和main里的嵌入维度就行。

**Comment by KokiaY** [comment]
感谢您的解答，请问Twitter数据集有处理成这篇论文使用的格式的代码吗，或者已经处理好的数据。其次是/p  /n等是什么意思呢？

**Comment by Venu-ka** [comment]
> 感谢您的解答，请问Twitter数据集有处理成这篇论文使用的格式的代码吗，或者已经处理好的数据。其次是/p /n等是什么意思呢？

论文里有说，p（表示积极情感），n（表示消极情感），o（表示中性情感）

**Comment by KokiaY** [comment]
Thanks♪(･ω･)ﾉ

**Comment by UACurry** [comment]
请问用bert时候 需要修改哪些吗，我目前没跑起来bert
